name: Build UI

on: [workflow_dispatch]

jobs:
  build_push_docker:
name: Push Docker image to Docker Hub after building
runs-on: ubuntu-latest
steps:
  - name: Check out the repo
    uses: actions/checkout@v2
  
  - name: 'Set up JDK 1.8'
    uses: actions/setup-java@v1
    with:
      java-version: 8
      
  - name: 'Checkout submodules'
    uses: textbook/git-checkout-submodule-action@master
    
  - name: 'Install 32-bit dependencies'
    run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6 ant
    
  - name: 'Make Auth Key'
    run: ant MakeAuthKey
    
    working-directory: appinventor
  - name: 'Build Appinventor'
    run: ant noplay        
    working-directory: appinventor

  
  - name: Log in to Docker Hub
    uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    with:
      username: ${{ secrets.DH_USERNAME }}
      password: ${{ secrets.DH_PASSWORD }}
  
  - name: Extract metadata (tags, labels) for Docker
    id: meta
    uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    with:
      images: ${{ secrets.DH_USERNAME }}/ai2
      
  - name: Build and push Docker image
    uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
    with:
      context: .
      push: true
      tags: ${{ secrets.DH_USERNAME }}/ai2:${{ github.sha }}
      labels: ${{ secrets.DH_USERNAME }}/ai2:${{ github.sha }}
